### ISSUE TITLE
[Suggestion]: Group Item Tag for Vats

### ISSUE THREAD

**Issue by TheBedrockMaster** [Mrbysco/OreBerries-Replanted#11]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

It would be useful if all vats had a specific item tag. For example oreberriesreplanted:vats.

**Comment by Mrbysco** [comment]
I forgot to implement this, will do it later today
