### ISSUE TITLE
[Suggestion]: Release Update

### ISSUE THREAD

**Issue by Hiranus** [Mrbysco/OreBerries-Replanted#15]
### General Info

- [ ] I would like to propose new content
- [ ] I would like to propose changes
- [X] I would like to propose another thing

### Suggestion Description

Please release update for 1.21.1 
Thanks.

**Comment by Mrbysco** [comment]
An update with what? there hasn't been any unreleased changes

**Comment by Hiranus** [comment]
> An update with what? there hasn't been any unreleased changes

![image](https://github.com/user-attachments/assets/bf55f1e5-c479-45e9-8806-2019882ec0aa)
100 mb fix is still not released.

**Comment by Mrbysco** [comment]
0.9.6 contains the fix and is available on curseforge
