### ISSUE TITLE
[Suggestion]: A dimension blacklist.

### ISSUE THREAD

**Issue by Gbergz** [Mrbysco/OreBerries-Replanted#2]
### General Info

- [X] I would like to propose new content
- [ ] I would like to propose changes
- [ ] I would like to propose another thing

### Suggestion Description

A dimension blacklist would be lovely. Would prevent oreberries generating in dimensions where they shouldn't. Like in the Bumblezone mod dimension.

Preview: 
![image](https://user-images.githubusercontent.com/26634554/148960347-5acd353c-c236-464a-886d-d3dadfb2be88.png)

**-** Gbergz

**Comment by Mrbysco** [comment]
I stopped them from spawning in non-overworld dimensions in https://github.com/Mrbysco/OreBerries-Replanted/commit/570c394e0a4f3ec4b31a0d55b4101a6a47d6156e

**Comment by Gbergz** [comment]
Thank you. :)

**Comment by Mrbysco** [comment]
Thanks to you reporting this I managed to fix the same issue in multiple of my mods, thank you for reporting the bug :D
