### ISSUE TITLE
compatibility Issue with JEI and REI [Multiplayer] 1.18.2

### ISSUE THREAD

**Issue by IchigoGames** [Mrbysco/OreBerries-Replanted#3]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.0

### Mod version

OreBerries-Replanted-1.18.2-0.1.6

### Java version

java 17

### Issue Description

With This Mod Added JEI stops working it will no longer show Recipes in multiplayer also with this mod added REI will not show anything in multiplayer.

Extra thing to note as i was working on getting you Logs i removed as meany mods as possible so it would be easer to read log but found with only this mod + JEI you cant connect to a Server At all. it will give your a error and wont let you connect. this may be related or could be a separate bug.

### Additional Information
jei-1.18.2-9.7.0.194

Clint log [latest.log](https://github.com/Mrbysco/OreBerries-Replanted/files/8598210/latest.log) with a few mods
Clint log [latest.log](https://github.com/Mrbysco/OreBerries-Replanted/files/8598217/latest.log) with Only this mod + JEI
Server log [latest.log](https://github.com/Mrbysco/OreBerries-Replanted/files/8598228/latest.log)

https://github.com/mezz/JustEnoughItems/issues/2808

**Comment by IchigoGames** [comment]
also after removing this mod REI that would not show in game on multiplayer without first loading into single player started to work again. so i think its affecting both mods

**Comment by IchigoGames** [comment]
btw this may be fixed with JEI but still does not work on servers with REI @Mrbysco

**Comment by Mrbysco** [comment]
Oreberries Replanted doesn't ship REI support, so if anything's broken it's REI's implementation of the JEI internals
