### ISSUE TITLE
[Bug]: Latest 1.18.2 version incorrectly reads/writes reciepe packets on multiplayer server enviornment.

### ISSUE THREAD

**Issue by ShibeTemple** [Mrbysco/OreBerries-Replanted#4]
### General Info

- [X] I am running a modpack
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [X] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.25

### Mod version

0.1.6

### Java version

64bit 1.8.0_312-b07 Temurin

### Issue Description

The OreBerries Replanted mod when installed on a multiplayer server, corrupts the recipe packets being sent to the client. This results in one of two reproducible outcomes: (1) JEI not being able to work properly, or (2) the client refusing to connect due to malformed datapack. This issue was originally brought up with JEI, but the issue persists when JEI is not present. The issue lies with Oreberries. https://github.com/mezz/JustEnoughItems/issues/2832 Server logs, client logs, and screenshots of client errors are all within that issue tracker.

**Comment by Mrbysco** [comment]
Invalid issue, 0.1.6 is NOT the latest version. The latest version 0.1.7 released almost a MONTH ago fixes this already

**Comment by Mrbysco** [comment]
This has been fixed ever since it was reported a month ago when https://github.com/mezz/JustEnoughItems/issues/2808 was made

**Comment by ShibeTemple** [comment]
Strange, curseforge reports it as still being the latest valid version. 

![image](https://user-images.githubusercontent.com/6219801/170826065-478ff721-e3e4-404a-ba55-48e281d82673.png)

Although, I see this is not the case on the actual project page. Must be a curseforge issue.
