### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Aaron732** [Mrbysco/OreBerries-Replanted#6]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

40.1.80

### Minecraft version

1.18.2

### Mod version

0.1.7

### Java version

IDK

### Issue Description

Hello,
I am creating a modpack and noticed that the bushes are growing **very very slowly** and would like to know if this is normal and if this can be **changed**. I would also like to know if there was a way to **add** bushes. Thank you and good day.

**Comment by Mrbysco** [comment]
There's currently no way to speed them up but I could add a config value.
I can't say the same for adding new ones as each texture is hand-made for the specific ore variant

**Comment by Aaron732** [comment]
Cool but is there a way i can add bushes and add texture?

**Comment by Mrbysco** [comment]
No

**Comment by Mrbysco** [comment]
Scratch that... There should be a `growthChance` config option that if changed to be smaller it makes it grow faster
