### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by raalpe** [Mrbysco/OreBerries-Replanted#8]
### General Info

- [X] I am running a modpack
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the mod

### Forge version

Neoforge 47.21.76 version independent issue

### Minecraft version

1.20.1

### Mod version

0.5.0

### Java version

Java 8 Version 381

### Issue Description

the implementation of berry to nugget recipe registers as a valid smelting/blasting recipe that only yields experience.
this bug occour with other mods' furnaces that accept the default smelting/blasting tag, and the recipe shows up in JEI.

Additionally when using REI it also showcases default minecraft smelting/recipes that is invalid.

based on:
https://github.com/FTBTeam/FTB-Modpack-Issues/issues/3798

**Comment by Mrbysco** [comment]
I've fixed the issue and a new version is being uploaded

**Comment by Mrbysco** [comment]
https://curseforge.com/minecraft/mc-mods/oreberries-replanted/files/4760372
